services:
  api:
    image: "node:${VERSION_NODE}"
    command: "yarn start:dev"
    user: node
    working_dir: /home/node/nest
    environment:
      - PUERTO_NESTJS=${PUERTO_NEST}
      - DB_HOST=${RUTA_DB}
      - DB_PORT=${PUERTO_DB}
      - DB_USER=${USUARIO_DB}
      - DB_PASS=${CLAVE_ROOT_DB}
      - DB_NAME=${NOMBRE_DB}
    ports:
      - "5001:${PUERTO_NEST}"
    volumes:
      - .:/home/node/nest
  db:
    image: "mysql:${VERSION_DB}"
    environment:
      MYSQL_ROOT_PASSWORD: ${CLAVE_ROOT_DB}
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "5002:${PUERTO_DB}"