services:
  api:
    image: "node:${VERSION_NODE}"
    command: "yarn start:dev"
    user: node
    working_dir: /home/node/nest
    environment:
      - PUERTO_NESTJS=${PUERTO_NEST}
      - DB_HOST=${RUTA_DB}
      - DB_PORT=${PUERTO_DB}
      - DB_USER=${USUARIO_DB}
      - DB_PASS=${CLAVE_ROOT_DB}
      - DB_NAME=${NOMBRE_DB}
    ports:
      - "5001:${PUERTO_NEST}"
    volumes:
      - .:/home/node/nest
  db:
    image: "mysql:${VERSION_DB}"
    environment:
      MYSQL_ROOT_PASSWORD: ${CLAVE_ROOT_DB}
      MYSQL_DATABASE: ${NOMBRE_DB}
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "5002:${PUERTO_DB}"
  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ./scripts:/flyway/sql
    command: -url=jdbc:mysql://${RUTA_DB}:${PUERTO_DB}/${NOMBRE_DB} -user=${USUARIO_DB} -password=${CLAVE_ROOT_DB} -connectRetries=60 migrate