services:
  api:
    image: "jorgemparrah/tareas:${VERSION_TAG}"
    environment:
      - PUERTO_NESTJS=${PUERTO_NEST}
      - DB_HOST=${RUTA_DB}
      - DB_PORT=${PUERTO_DB}
      - DB_USER=${USUARIO_DB}
      - DB_PASS=${CLAVE_ROOT_DB}
      - DB_NAME=${NOMBRE_DB}
    ports:
      - "3000:${PUERTO_NEST}"
  db:
    image: "mysql:${VERSION_DB}"
    environment:
      MYSQL_ROOT_PASSWORD: ${CLAVE_ROOT_DB}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:${PUERTO_DB}"